api/urls.py
from django.conf.urls import url
from api import views


urlpatterns = [
    url(r'^person_detail/(?P<person_id>\d+)$', views.PersonDetailView.as_view(), name='person_detail'),
]

attendance/urls.py
from django.conf.urls import url
from attendance import views


urlpatterns = [
    url(r'^home/$', views.AttendanceHomeView.as_view(), name='home'),
    url(r'^add_practice/$', views.PracticeAddView.as_view(), name='add_practice'),
    url(r'^choir_list/(?P<practice_id>\d+)/(?P<part>\w+)$', views.ChoirListView.as_view(), name='choir_list'),
    url(r'^add_person/$', views.PersonAddView.as_view(), name='add_person'),
    url(r'^edit_person/(?P<person_id>\d+)$', views.PersonEditView.as_view(), name='edit_person'),
    url(r'^update_attendance/$', views.AttendanceEditView.as_view(), name='update_attendance'),
    url(r'^make_inactive_member/$', views.InactivePersonView.as_view(), name='make_inactive_member'),
    url(r'^make_active_member/$', views.ActivePersonView.as_view(), name='make_active_member'),
    url(r'^delete_person/$', views.PersonDeleteView.as_view(), name='delete_person'),
]

choir/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from choir import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^song/', include('song.urls', namespace='song')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$', views.root),
]

attendance/models.py
from django.db import models
from django.utils import timezone


class Person(models.Model):

    PART_CHOICES = (
        ('S', '소프라노'),
        ('A', '알토'),
        ('T', '테너'),
        ('B', '베이스'),
    )

    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    birth = models.CharField(max_length=10)
    birth_monthday = models.CharField(max_length=4, default='')
    part = models.CharField(max_length=1, choices=PART_CHOICES)
    is_active = models.BooleanField(default=True)
    create_dt = models.DateTimeField(default=timezone.now)


class Song(models.Model):
    no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=40)
    author = models.CharField(max_length=60)
    play_time = models.CharField(max_length=20)


class Practice(models.Model):
    song = models.ForeignKey(Song)
    practice_dt = models.DateField()
    create_dt = models.DateTimeField(default=timezone.now)


class Attendance(models.Model):
    person = models.ForeignKey(Person)
    practice = models.ForeignKey(Practice)
    is_join = models.BooleanField(default=False)

attendance/views.py
import calendar
import logging

from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Count, Case, When, IntegerField
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.views.generic import View
from datetime import datetime, timedelta, date

from rest_framework.response import Response
from rest_framework.views import APIView

from attendance.models import Song, Practice, Person, Attendance
from choir.common.api_result import APIResult, APIStatusMessage, APIResultSerializer
from choir.common.api_result import APIStatusCode


class AttendanceHomeView(View):

    def get(self, request):

        last_practice = Practice.objects.last()

        if last_practice:
            attendance_info = Attendance.objects.select_related('person').filter(
                practice=last_practice.id, is_join=True).aggregate(
                attendance_count=Count('id'),
                s_count=Count(Case(When(person__part='S', then=1), output_field=IntegerField())),
                a_count=Count(Case(When(person__part='A', then=1), output_field=IntegerField())),
                t_count=Count(Case(When(person__part='T', then=1), output_field=IntegerField())),
                b_count=Count(Case(When(person__part='B', then=1), output_field=IntegerField()))
            )
        else:
            attendance_info = None

        today = datetime.now().date()
        last_day = calendar.monthrange(today.year, today.month)[1]
        first_date = date(today.year, today.month, 1).strftime('%m%d')
        last_date = date(today.year, today.month, last_day).strftime('%m%d')
        birthday_list = Person.objects.filter(
            birth_monthday__gte=first_date, birth_monthday__lte=last_date, is_active=True).all()

        logging.info(birthday_list)
        context = {
            'last_practice': last_practice,
            'attendance_info': attendance_info,
            'birthday_list': birthday_list
        }

        return TemplateResponse(request, 'attendance/home.html', context)


class PracticeAddView(View):

    def get(self, request):

        song_list = Song.objects.all().order_by('-no')

        context = {
            'practice_dt': datetime.now(),
            'song_list': song_list
        }

        return TemplateResponse(request, 'attendance/add_practice.html', context)

    def post(self, request):

        practice_dt = request.POST.get('practice_dt')
        song_no = request.POST.get('song')

        song = Song.objects.get(pk=song_no)
        person_list = Person.objects.all()
        attendance_list = []

        with transaction.atomic():
            practice = Practice()
            practice.practice_dt = practice_dt
            practice.song = song
            practice.save()

            for person in person_list:
                attendance = Attendance()
                attendance.practice = practice
                attendance.person = person
                attendance_list.append(attendance)

            Attendance.objects.bulk_create(attendance_list)

        return HttpResponseRedirect(reverse('attendance:home'))


class ChoirListView(View):

    def get(self, request, practice_id, part):
        year = str(datetime.now().year)
        person_list = Attendance.objects.select_related('person', 'practice').filter(
            practice__id=practice_id, person__part=part, person__is_active=True
        ).order_by('person__name')

        inactive_person_list = Attendance.objects.select_related('person', 'practice').filter(
            practice__id=practice_id, person__part=part, person__is_active=False
        ).order_by('person__name')

        attendance_info_list = Attendance.objects.select_related('person', 'practice').values('person').filter(
            person__part=part, practice__practice_dt__istartswith=year
        ).annotate(
            join_count=Count(Case(When(is_join=True, then=1))),
            absent_count=Count(Case(When(is_join=False, then=1))),
        )

        attendance_map = {}
        for attendance_info in attendance_info_list:
            key = 'P{}'.format(attendance_info['person'])
            practice_count = attendance_info['join_count'] + attendance_info['absent_count']
            value = round(attendance_info['join_count'] * 100 / practice_count)
            attendance_map[key] = value
        # logging.info(person_list)

        for person in person_list:
            key = 'P{}'.format(person.person_id)
            setattr(person, 'join_rate', attendance_map[key])

        if part == 'S':
            part_string = '소프라노'
            label_color = 'label-info'
        elif part == 'A':
            part_string = '알토'
            label_color = 'label-warning'
        elif part == 'T':
            part_string = '테너'
            label_color = 'label-success'
        elif part == 'B':
            part_string = '베이스'
            label_color = 'label-primary'
        else:
            # error.
            pass

        context = {
            'part': part,
            'part_string': part_string,
            'label_color': label_color,
            'person_list': person_list,
            'inactive_person_list': inactive_person_list,
        }

        return TemplateResponse(request, 'attendance/choir_list.html', context)


class PersonAddView(View):

    def get(self, request):

        part = request.GET.get('part')
        practice = Practice.objects.last()

        context = {
            'part': part,
            'practice': practice
        }

        return TemplateResponse(request, 'attendance/add_person.html', context)

    def post(self, request):

        name = request.POST.get('name')
        part = request.POST.get('part')
        birth = request.POST.get('birth')
        phone = request.POST.get('phone')
        practice_id = request.POST.get('practice_id')

        if birth and birth != '':
            birth_monthday = birth[2:6]

        with transaction.atomic():
            person = Person()
            person.name = name
            person.part = part
            person.birth = birth
            person.birth_monthday = birth_monthday
            person.phone = phone
            person.save()

            practice = Practice.objects.get(pk=practice_id)

            attendance = Attendance()
            attendance.practice = practice
            attendance.person = person

            attendance.save()

        return HttpResponseRedirect(reverse('attendance:choir_list', kwargs={'practice_id': practice_id, 'part': part}))


class AttendanceEditView(APIView):

    def post(self, request):

        person_id = request.POST.get('person_id')
        practice_id = request.POST.get('practice_id')
        is_join = request.POST.get('is_join')

        api_result = APIResult()

        try:
            attendance = Attendance.objects.get(person=person_id, practice=practice_id)

            if is_join == 'true':
                attendance.is_join = True
            else:
                attendance.is_join = False

            attendance.save()
        except:
            api_result.status = APIStatusCode.ERROR
            api_result.message = APIStatusMessage.ERROR

        return Response(APIResultSerializer(api_result).data)


class PersonEditView(View):

    def get(self, request, person_id):

        person = Person.objects.get(pk=person_id)
        practice = Practice.objects.last()
        context = {
            'person': person,
            'practice': practice
        }
        return TemplateResponse(request, 'attendance/edit_person.html', context)

    def post(self, request, person_id):

        name = request.POST.get('name')
        part = request.POST.get('part')
        birth = request.POST.get('birth')
        phone = request.POST.get('phone')
        origin_part = request.POST.get('origin_part')
        practice_id = request.POST.get('practice_id')
        if birth and birth != '':
            birth_monthday = birth[2:6]

        Person.objects.filter(pk=person_id).update(
            name=name, part=part, birth=birth, phone=phone, birth_monthday=birth_monthday
        )

        return HttpResponseRedirect(reverse('attendance:choir_list', kwargs={'practice_id': practice_id, 'part': origin_part}))


class InactivePersonView(APIView):

    def post(self, request):

        person_id = request.POST.get('person_id')

        api_result = APIResult()

        try:
            Person.objects.filter(pk=person_id).update(is_active=False)
        except:
            api_result.status = APIStatusCode.ERROR
            api_result.message = APIStatusMessage.ERROR

        return Response(APIResultSerializer(api_result).data)


class ActivePersonView(APIView):

    def post(self, request):

        person_id = request.POST.get('person_id')

        api_result = APIResult()

        try:
            Person.objects.filter(pk=person_id).update(is_active=True)
        except:
            api_result.status = APIStatusCode.ERROR
            api_result.message = APIStatusMessage.ERROR

        return Response(APIResultSerializer(api_result).data)


class PersonDeleteView(APIView):

    def post(self, request):

        person_id = request.POST.get('person_id')

        api_result = APIResult()

        try:
            Person.objects.filter(pk=person_id).delete()
        except:
            api_result.status = APIStatusCode.ERROR
            api_result.message = APIStatusMessage.ERROR

        return Response(APIResultSerializer(api_result).data)

attendance/templates/attendance/add_person.html
{% extends "common/base.html" %}

{% block css %}
{% endblock %}

{% block content %}
{% autoescape off %}
    <div class="col-xs-12">
        <h3 class="pull-left">대원 등록</h3>
        <hr class="clear"/>
    </div>

    <div class="col-xs-12">

        <form action="{% url 'attendance:add_person' %}" class="form-horizontal" method="post" onsubmit="return valid_check();">
            {% csrf_token %}
            <input type="hidden" name="practice_id" value="{{ practice.id }}" />
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="form-group">
                        <label for="category" class="col-xs-3 control-label">이름</label>
                        <div class="col-xs-6">
                            <input name="name" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-3 control-label">파트</label>
                        <div class="col-xs-9">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="part" value="S" checked="checked"> 소프라노
                                </label>
                                <label>
                                    <input type="radio" name="part" value="A" {% if part == 'A' %}checked{% endif %}> 알토
                                </label>
                                <label>
                                    <input type="radio" name="part" value="T" {% if part == 'T' %}checked{% endif %}> 테너
                                </label>
                                <label>
                                    <input type="radio" name="part" value="B" {% if part == 'B' %}checked{% endif %}> 베이스
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-3 control-label">생년월일</label>
                        <div class="col-xs-6">
                            <input id="birth" name="birth" type="number" class="form-control input-sm" placeholder="YYMMDD 6자리 입력" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-3 control-label">전화번호</label>
                        <div class="col-xs-6">
                            <input name="phone" type="tel" class="form-control input-sm" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <button type="submit" class="btn btn-primary">등록</button>
                            <a href="{% url 'attendance:choir_list' practice.id part %}" class="btn btn-default">취소</a>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>
{% endautoescape %}
{% endblock %}

{% block scripts %}

    <script type="text/javascript">
        function valid_check() {
            var re = /[0-9]+/;
            var birth = $("#birth").val();
            if(re.test(birth)){
                if(birth.length != 6) {
                    alert("YYMMDD 형태로 입력해주세요.");
                    return false;
                }
                return true;
            } else {
                return false;
            }

        }
        $(document).ready(function () {

        });
    </script>
{% endblock %}

attendance/templates/attendance/choir_list.html
{% extends "common/base.html" %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootswitch/css/bootstrap3/bootstrap-switch.min.css' %}" />
    <style type="text/css">
        label { color:#fff; padding:6px; }
        .clear { clear:both; }
        table th, td { text-align: center; }
    </style>

{% endblock %}

{% block content %}
<div class="col-xs-12">
    <label class="{{ label_color }}">{{ part_string }} <span class="badge">{{ person_list|length }}</span></label>
    <div class="pull-right">
        <a href="{% url 'attendance:add_person' %}?part={{ part }}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"> 대원추가</span>
        </a>
    </div>

    <div class="panel clear">
        <table class="table table-condensed">
            <thead>
            <th>이름</th>
            <th>생년월일</th>
            <th>출석률</th>
            <th>수정</th>
            <th>출석체크</th>
            </thead>
            <tbody>
                {% for item in person_list %}
                    <tr>
                        <td>{{ item.person.name }}</td>
                        <td>{{ item.person.birth }}</td>
                        <td>{{ item.join_rate }}%</td>
                        <td><a href="{% url 'attendance:edit_person' item.person.id %}" class="btn btn-success btn-xs">수정</a></td>
                        <td>
                            <input type="checkbox" data-on-text="출석" data-off-text="결석" data-size="mini" data-person-id="{{ item.person.id }}" data-practice-id="{{ item.practice.id }}" {% if item.is_join == True %}checked{% endif %}>
                        </td>
                    </tr>
                {% empty %}
                <tr>
                    <td colspan="5" class="text-center">
                        <p></p>
                        <p>등록된 대원이 없습니다.</p>
                        <p></p>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr/>
        <h4>휴면대원</h4>
        <table class="table table-condensed">
            <thead>
            <th>이름</th>
            <th>생년월일</th>
            <th>수정</th>
            <th></th>
            </thead>
            <tbody>
            {% for item in inactive_person_list %}
                <tr>
                    <td>{{ item.person.name }}</td>
                    <td>{{ item.person.birth }}</td>
                    <td><a href="{% url 'attendance:edit_person' item.person.id %}" class="btn btn-success btn-xs">수정</a></td>
                    <td>
                        <button class="btn btn-xs btn-warning" onclick="make_active_member({{ item.person.id }});">휴면해제</button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">
                        <p></p>
                        <p>등록된 대원이 없습니다.</p>
                        <p></p>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'lib/bootswitch/js/bootstrap-switch.min.js' %}"></script>
    <script type="text/javascript">
        function updateAttendance(e, state) {
            $.ajax({
                url: "{% url 'attendance:update_attendance' %}",
                type: 'POST',
                data: {
                    'person_id': $(this).attr('data-person-id'),
                    'practice_id': $(this).attr('data-practice-id'),
                    'is_join': state,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    console.log(response);
                },
                error: function(error) {
                    alert('에러가 발생하였습니다. 다시 시도해주세요.');
                    //location.reload();
                }
            });
        }

        function make_active_member(person_id) {
            $.ajax({
                url: "{% url 'attendance:make_active_member' %}",
                type: 'POST',
                data: {
                    'person_id': person_id
                },
                success: function(response) {
                    location.reload();
                },
                error: function(error) {
                    alert('에러가 발생하였습니다. 다시 시도해주세요.');
                    //location.reload();
                }
            });
        }

        $(document).ready(function() {
            $("input:checkbox").bootstrapSwitch();
            $("input:checkbox").on('switchChange.bootstrapSwitch', updateAttendance);

        });
    </script>
{% endblock %}

attendance/templates/attendance/edit_person.html
{% extends "common/base.html" %}

{% block css %}
{% endblock %}

{% block content %}
{% autoescape off %}
    <div class="col-xs-12">
        <h3 class="pull-left">대원 정보 수정</h3>
    </div>

    <div class="col-xs-12">

        <form action="{% url 'attendance:edit_person' person.id %}" class="form-horizontal" method="post" onsubmit="return valid_check();">
            {% csrf_token %}
            <input type="hidden" name="practice_id" value="{{ practice.id }}" />
            <input type="hidden" name="origin_part" value="{{ person.part }}" />
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">이름</label>
                        <div class="col-xs-8">
                            <input name="name" type="text" class="form-control input-sm" value="{{ person.name }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">파트</label>
                        <div class="col-xs-8">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="part" value="S" checked="checked"> 소프라노
                                </label>
                                <label>
                                    <input type="radio" name="part" value="A" {% if person.part == 'A' %}checked{% endif %}> 알토
                                </label>
                                <br />
                                <label>
                                    <input type="radio" name="part" value="T" {% if person.part == 'T' %}checked{% endif %}> 테너
                                </label>
                                <label>
                                    <input type="radio" name="part" value="B" {% if person.part == 'B' %}checked{% endif %}> 베이스
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">생년월일</label>
                        <div class="col-xs-8">
                            <input id="birth" name="birth" type="number" class="form-control input-sm" value="{{ person.birth }}" placeholder="YYMMDD 6자리 입력" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">전화번호</label>
                        <div class="col-xs-8">
                            <input name="phone" type="tel" class="form-control input-sm" value="{{ person.phone }}" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <button type="submit" class="btn btn-primary btn-sm">저장</button>
                            <a href="{% url 'attendance:choir_list' practice.id person.part %}" class="btn btn-default brn-sm">취소</a>
                            {% if person.is_active %}
                                <button id="btn_inactive_member" type="button" class="btn btn-warning btn-sm">휴면대원처리</button>
                            {% else %}
                                <button id="btn_active_member" type="button" class="btn btn-warning btn-sm">휴면해제</button>
                            {% endif %}
                            <button id="btn_delete" type="button" class="btn btn-danger btn-sm">삭제</button>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>
{% endautoescape %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        function valid_check() {
            var re = /[0-9]+/;
            var birth = $("#birth").val();
            if(re.test(birth)){
                if(birth.length != 6) {
                    alert("YYMMDD 형태로 입력해주세요.");
                    return false;
                }
                return true;
            } else {
                return false;
            }

        }

        function make_inactive_member() {
            $.ajax({
                url: "{% url 'attendance:make_inactive_member' %}",
                type: 'POST',
                data: {
                    'person_id': {{ person.id }}
                },
                success: function(response) {
                    location.href = "{% url 'attendance:choir_list' practice.id person.part %}";
                },
                error: function(error) {
                    alert('에러가 발생하였습니다. 다시 시도해주세요.');
                    //location.reload();
                }
            });
        }

        function make_active_member() {
            $.ajax({
                url: "{% url 'attendance:make_active_member' %}",
                type: 'POST',
                data: {
                    'person_id': {{ person.id }}
                },
                success: function(response) {
                    location.href = "{% url 'attendance:choir_list' practice.id person.part %}";
                },
                error: function(error) {
                    alert('에러가 발생하였습니다. 다시 시도해주세요.');
                    //location.reload();
                }
            });
        }

        function delete_person() {

            if(!confirm("대원정보를 삭제하시겠습니까?"))
                return false;

            $.ajax({
                url: "{% url 'attendance:delete_person' %}",
                type: 'POST',
                data: {
                    'person_id': {{ person.id }}
                },
                success: function(response) {
                    location.href = "{% url 'attendance:choir_list' practice.id person.part %}";
                },
                error: function(error) {
                    alert('에러가 발생하였습니다. 다시 시도해주세요.');
                    //location.reload();
                }
            });
        }

        $(document).ready(function () {
            $("#btn_inactive_member").on("click", make_inactive_member);
            $("#btn_active_member").on("click", make_active_member);
            $("#btn_delete").on("click", delete_person);
        });
    </script>
{% endblock %}

attendance/templates/attendance/home.html
{% extends "common/base.html" %}

{% block css %}
    <style type="text/css">
        div.attendance-group a { width:100%; }
    </style>

{% endblock %}

{% block content %}
<div class="col-xs-12">
    <div>
        <div class="panel panel-default">
            <div class="panel-heading">
                오늘의 연습곡
                <a href="{% url 'attendance:add_practice' %}" id="btn_new_practice" class="btn btn-default btn-xs pull-right">새연습 일정 추가</a>
            </div>
            <div class="panel-body">
                {% if last_practice %}
                <h5>날짜 : {{ last_practice.practice_dt|date:"Y-m-d" }}</h5>
                <h5>제목 : {{ last_practice.song.title }}</h5>
                <h5>작사/작곡 : {{ last_practice.song.author }}</h5>
                <h5>소요시간 : {{ last_practice.song.play_time }}</h5>
                <h5>
                    출석 대원수 : {{ attendance_info.attendance_count }}명
                    ( S: {{ attendance_info.s_count }}, A: {{ attendance_info.a_count }}, T: {{ attendance_info.t_count }}, B: {{ attendance_info.b_count }} )
                </h5>
                {% else %}
                <h5>마지막으로 진행한 연습이 없습니다.</h5>
                <h5>새 연습 일정을 추가해주세요.</h5>
                {% endif %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                이번달 생일자
            </div>
            <div class="panel-body">
                <ul>
                {% for person in birthday_list %}
                    <li>{{ person.name }} {{ person.birth_monthday }} / {{ person.get_part_display }} </li>
                {% empty %}
                    <p>이번달 생일자가 없습니다.</p>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% if last_practice %}
    <div class="attendance-group">
        <p>
            <a href="{% url 'attendance:choir_list' last_practice.id 'S' %}" class="btn btn-info btn-lg">소프라노 출석부</a>
        </p>
        <p>
            <a href="{% url 'attendance:choir_list' last_practice.id 'A' %}" class="btn btn-warning btn-lg">알토 출석부</a>
        </p>
        <p>
            <a href="{% url 'attendance:choir_list' last_practice.id 'T' %}" class="btn btn-success btn-lg">테너 출석부</a>
        </p>
        <p>
            <a href="{% url 'attendance:choir_list' last_practice.id 'B' %}" class="btn btn-primary btn-lg">베이스 출석부</a>
        </p>
    </div>
    {% endif %}

</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
    });
</script>
{% endblock %}