api/urls.py
from django.conf.urls import url
from api import views


urlpatterns = [
    url(r'^person_detail/(?P<person_id>\d+)$', views.PersonDetailView.as_view(), name='person_detail'),
]

choir/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from choir import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^song/', include('song.urls', namespace='song')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$', views.root),
]

song/urls.py
from django.conf.urls import url
from song import views


urlpatterns = [
    url(r'^home/$', views.SongHomeView.as_view(), name='home'),
    url(r'^add/$', views.SongAddView.as_view(), name='add'),
    url(r'^edit/(?P<song_no>\d+)$', views.SongEditView.as_view(), name='edit'),
]

song/models.py
from django.db import models

# Create your models here.

song/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.views.generic import View

from attendance.models import Song


class SongHomeView(View):

    def get(self, request):

        song_list = Song.objects.all().order_by('-no')

        context = {
            'song_list': song_list
        }

        return TemplateResponse(request, 'song/home.html', context)


class SongAddView(View):

    def get(self, request):

        return TemplateResponse(request, 'song/add.html')

    def post(self, request):

        no = request.POST.get('no')
        title = request.POST.get('title')
        author = request.POST.get('author')
        play_time = request.POST.get('play_time')

        song = Song()
        song.no = no
        song.title = title
        song.author = author
        song.play_time = play_time
        song.save()

        return HttpResponseRedirect(reverse('song:home'))


class SongEditView(View):

    def get(self, request, song_no):

        song = Song.objects.get(pk=song_no)

        context = {
            'song': song
        }
        return TemplateResponse(request, 'song/edit.html', context)

    def post(self, request, song_no):

        no = request.POST.get('no')
        title = request.POST.get('title')
        author = request.POST.get('author')
        play_time = request.POST.get('play_time')

        Song.objects.filter(pk=song_no).update(
            no=no, title=title, author=author, play_time=play_time
        )

        return HttpResponseRedirect(reverse('song:home'))

song/templates/song/add.html
{% extends "common/base.html" %}

{% block css %}
{% endblock %}

{% block content %}
{% autoescape off %}
    <div class="col-xs-12">
        <h3 class="pull-left">악보 등록</h3>
        <hr class="clear"/>
    </div>

    <div class="col-xs-12">

        <form action="{% url 'song:add' %}" class="form-horizontal" method="post">
            {% csrf_token %}

            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">NO</label>
                        <div class="col-xs-8">
                            <input name="no" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">제목</label>
                        <div class="col-xs-8">
                            <input name="title" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">작사/작곡</label>
                        <div class="col-xs-8">
                            <input name="author" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">소요시간</label>
                        <div class="col-xs-8">
                            <input name="play_time" type="text" class="form-control input-sm" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <button type="submit" class="btn btn-primary">등록</button>
                            <a href="{% url 'song:home' %}" class="btn btn-default">취소</a>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>
{% endautoescape %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
{% endblock %}

song/templates/song/edit.html
{% extends "common/base.html" %}

{% block css %}
{% endblock %}

{% block content %}
{% autoescape off %}
    <div class="col-xs-12">
        <h3 class="pull-left">악보 정보 수정</h3>
        <hr class="clear"/>
    </div>

    <div class="col-xs-12">

        <form action="{% url 'song:edit' song.no %}" class="form-horizontal" method="post">
            {% csrf_token %}

            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">NO</label>
                        <div class="col-xs-8">
                            <input name="no" type="text" class="form-control input-sm" value="{{ song.no }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">제목</label>
                        <div class="col-xs-8">
                            <input name="title" type="text" class="form-control input-sm" value="{{ song.title }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">작사/작곡</label>
                        <div class="col-xs-8">
                            <input name="author" type="text" class="form-control input-sm" value="{{ song.author }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="category" class="col-xs-4 control-label">소요시간</label>
                        <div class="col-xs-8">
                            <input name="play_time" type="text" class="form-control input-sm" value="{{ song.play_time }}" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <button type="submit" class="btn btn-primary">등록</button>
                            <a href="{% url 'song:home' %}" class="btn btn-default">취소</a>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>
{% endautoescape %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
{% endblock %}

song/templates/song/home.html
{% extends "common/base.html" %}

{% block css %}
    <style type="text/css">
    </style>

{% endblock %}

{% block content %}
<div class="col-xs-12">
    <div class="pull-right">
        <a href="{% url 'song:add' %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"> 악보추가</span>
        </a>
    </div>
    <div style="clear:both;" />
    <br />
    <div class="panel">
        <table id="song_list" class="table table-condensed">
            <thead>
            <th>NO</th>
            <th>제목</th>
            <th></th>
            </thead>
            <tbody>
                {% for item in song_list %}
                    <tr>
                        <td>{{ item.no }}</td>
                        <td>{{ item.title }}</td>
                        <td><a href="{% url 'song:edit' item.no %}" class="btn btn-success btn-xs">수정</a></td>
                    </tr>
                {% empty %}
                <tr>
                    <td colspan="2" class="text-center">
                        <p></p>
                        <p>등록된 악보가 없습니다.</p>
                        <p></p>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $("#song_list").DataTable({
		"order": [[ 0, "desc" ]]
	});
    });
</script>
{% endblock %}